#!/usr/bin/env python3

"""
test_keil_scatter.py - Tests for Keil/Arm armlink scatter file (.sct) parsing.

Covers:
  - Format detection (vs GNU LD, ICF, .emProject)
  - Typical uVision-generated scatter files (load + execution regions)
  - Attribute inference from selectors (+RO -> rx, +RW/+ZI -> rwx)
  - Attribute keywords: UNINIT, EMPTY (negative size), ALIGN <n>
  - Relative '+offset' execution region bases
  - Execution regions without an explicit max size
  - Load region shorthand (selectors directly in the load region)
  - Integration through LinkerScriptParser (transparent dispatch)
  - Coexistence with GNU LD scripts in one invocation
"""
# pylint: disable=missing-function-docstring,protected-access

import logging
import shutil
import tempfile
import unittest
from pathlib import Path

from membrowse.linker.base import LinkerFormatDetector
from membrowse.linker.keil_parser import KeilScatterParser
from membrowse.linker.parser import LinkerScriptError, LinkerScriptParser


_STM32_SCATTER = """\
; *************************************************************
; *** Scatter-Loading Description File generated by uVision ***
; *************************************************************

LR_IROM1 0x08000000 0x00080000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00080000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x00020000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
"""

_GNU_LD = """\
MEMORY
{
  FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 512K
  RAM (rwx)  : ORIGIN = 0x20000000, LENGTH = 128K
}
"""

_ICF = """\
define symbol __region_ROM_start__ = 0x08000000;
define memory mem with size = 4G;
define region FLASH = mem:[from 0x08000000 size 1M];
place in FLASH { readonly };
"""


class _ScatterTestBase(unittest.TestCase):
    """Shared setup for tests that need temp scatter files."""

    def setUp(self):
        self.temp_dir = Path(tempfile.mkdtemp())

    def tearDown(self):
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def _write(self, content, filename="app.sct"):
        path = self.temp_dir / filename
        path.write_text(content, encoding='utf-8')
        return str(path)


class TestKeilFormatDetection(unittest.TestCase):
    """Content-based detection of Keil scatter files."""

    def test_detects_uvision_scatter(self):
        self.assertTrue(LinkerFormatDetector.is_keil(_STM32_SCATTER))

    def test_detects_scatter_with_preprocessor_header(self):
        content = "#! armclang -E --target=arm-arm-none-eabi\n" + _STM32_SCATTER
        self.assertTrue(LinkerFormatDetector.is_keil(content))

    def test_rejects_gnu_ld_memory_block(self):
        self.assertFalse(LinkerFormatDetector.is_keil(_GNU_LD))

    def test_rejects_gnu_ld_sections_only(self):
        gnu = "SECTIONS\n{\n  .text 0x08000000 : { *(.text*) }\n}\n"
        self.assertFalse(LinkerFormatDetector.is_keil(gnu))

    def test_rejects_icf_content(self):
        self.assertFalse(LinkerFormatDetector.is_keil(_ICF))

    def test_rejects_emproject_content(self):
        xml = ('<!DOCTYPE CrossStudio_Project_File>\n'
               '<solution Name="App"><project Name="App" /></solution>')
        self.assertFalse(LinkerFormatDetector.is_keil(xml))

    def test_scatter_not_misclassified_as_icf(self):
        self.assertFalse(LinkerFormatDetector.is_icf(_STM32_SCATTER))

    def test_scatter_not_misclassified_as_emproject(self):
        self.assertFalse(LinkerFormatDetector.is_emproject(_STM32_SCATTER))


class TestKeilParserDirect(_ScatterTestBase):
    """Tests calling KeilScatterParser.parse() directly."""

    def test_typical_stm32_scatter(self):
        path = self._write(_STM32_SCATTER)
        regions = KeilScatterParser().parse(path)

        # Load region is not emitted when it has execution regions
        self.assertEqual(set(regions), {"ER_IROM1", "RW_IRAM1"})

        rom = regions["ER_IROM1"]
        self.assertEqual(rom.address, 0x08000000)
        self.assertEqual(rom.limit_size, 0x00080000)
        self.assertEqual(rom.attributes, "rx")
        self.assertEqual(rom.end_address, 0x0807FFFF)

        ram = regions["RW_IRAM1"]
        self.assertEqual(ram.address, 0x20000000)
        self.assertEqual(ram.limit_size, 0x00020000)
        self.assertEqual(ram.attributes, "rwx")

    def test_uninit_region(self):
        content = """\
LR_1 0x00000000 0x00100000 {
  ER_RO 0x00000000 0x00080000 { .ANY (+RO) }
  RW_NOINIT 0x20000000 UNINIT 0x00000400 { .ANY (+ZI) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        noinit = regions["RW_NOINIT"]
        self.assertEqual(noinit.address, 0x20000000)
        self.assertEqual(noinit.limit_size, 0x400)
        self.assertEqual(noinit.attributes, "rwx")

    def test_empty_region_with_negative_size(self):
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_RO 0x08000000 0x00080000 { .ANY (+RO) }
  ARM_LIB_STACK 0x20020000 EMPTY -0x400 { }
  ARM_LIB_HEAP 0x20010000 EMPTY 0x800 { }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        stack = regions["ARM_LIB_STACK"]
        # Negative size grows downwards from the base address
        self.assertEqual(stack.address, 0x2001FC00)
        self.assertEqual(stack.limit_size, 0x400)
        heap = regions["ARM_LIB_HEAP"]
        self.assertEqual(heap.address, 0x20010000)
        self.assertEqual(heap.limit_size, 0x800)

    def test_align_keyword_consumes_argument(self):
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_RO 0x08000000 ALIGN 8 0x00001000 { .ANY (+RO) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_RO"].limit_size, 0x1000)
        self.assertEqual(regions["ER_RO"].address, 0x08000000)

    def test_relative_offset_execution_region(self):
        content = """\
LR_IROM1 0x08000000 0x00080000 {
  ER_IROM1 0x08000000 0x00040000 { .ANY (+RO) }
  ER_IROM2 +0 0x00020000 { .ANY (+RO) }
  ER_IROM3 +0x10000 0x00010000 { .ANY (+RO) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_IROM2"].address, 0x08040000)
        self.assertEqual(regions["ER_IROM3"].address, 0x08070000)
        self.assertEqual(regions["ER_IROM3"].limit_size, 0x00010000)

    def test_exec_region_without_size_inherits_load_limit(self):
        content = """\
LR_1 0x00000000 0x00010000 {
  ER_1 0x00000000 { .ANY (+RO) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_1"].address, 0x0)
        self.assertEqual(regions["ER_1"].limit_size, 0x10000)

    def test_exec_region_without_size_outside_load_is_skipped(self):
        content = """\
LR_1 0x08000000 0x00010000 {
  ER_1 0x08000000 0x00010000 { .ANY (+RO) }
  RW_1 0x20000000 { .ANY (+RW +ZI) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertIn("ER_1", regions)
        self.assertNotIn("RW_1", regions)

    def test_load_region_shorthand_without_exec_regions(self):
        content = """\
LR_ROM 0x08000000 0x00080000 {
  .ANY (+RO)
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(set(regions), {"LR_ROM"})
        self.assertEqual(regions["LR_ROM"].address, 0x08000000)
        self.assertEqual(regions["LR_ROM"].limit_size, 0x00080000)
        self.assertEqual(regions["LR_ROM"].attributes, "rx")

    def test_decimal_literals(self):
        content = """\
LR_1 134217728 524288 {
  ER_1 134217728 524288 { .ANY (+RO) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_1"].address, 0x08000000)
        self.assertEqual(regions["ER_1"].limit_size, 0x00080000)

    def test_attribute_fallback_from_region_name(self):
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_FLASH 0x08000000 0x00040000 { }
  RW_SRAM 0x20000000 0x00010000 { }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_FLASH"].attributes, "rx")
        self.assertEqual(regions["RW_SRAM"].attributes, "rwx")

    def test_duplicate_region_later_wins(self):
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_1 0x08000000 0x00010000 { .ANY (+RO) }
}
LR_2 0x08080000 0x00080000 {
  ER_1 0x08080000 0x00020000 { .ANY (+RO) }
}
"""
        regions = KeilScatterParser().parse(self._write(content))
        self.assertEqual(regions["ER_1"].address, 0x08080000)
        self.assertEqual(regions["ER_1"].limit_size, 0x00020000)

    def test_unbalanced_braces_raise(self):
        content = "LR_1 0x0 0x1000 {\n  ER_1 0x0 0x1000 { .ANY (+RO) }\n"
        with self.assertRaises(LinkerScriptError):
            KeilScatterParser().parse(self._write(content))

    def test_no_regions_raises(self):
        with self.assertRaises(LinkerScriptError):
            KeilScatterParser().parse(self._write("; just a comment\n"))

    def test_unbalanced_braces_are_logged(self):
        content = "LR_1 0x0 0x1000 {\n  ER_1 0x0 0x1000 { .ANY (+RO) }\n"
        with self.assertLogs(
                "membrowse.linker.keil_parser", level="ERROR") as cm:
            with self.assertRaises(LinkerScriptError):
                KeilScatterParser().parse(self._write(content))
        self.assertTrue(any("unbalanced" in m for m in cm.output))

    def test_non_utf8_scatter_file_parses(self):
        # A stray non-UTF-8 byte (e.g. latin-1 comment) must not abort parsing.
        path = self.temp_dir / "app.sct"
        text = (
            "; \xa9 copyright\n"
            "LR_1 0x08000000 0x00080000 {\n"
            "  ER_1 0x08000000 0x00010000 { .ANY (+RO) }\n"
            "}\n"
        )
        path.write_bytes(text.encode("latin-1"))
        regions = KeilScatterParser().parse(str(path))
        self.assertIn("ER_1", regions)

    def test_overlapping_regions_are_logged(self):
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_1 0x08000000 0x00020000 { .ANY (+RO) }
  ER_2 0x08010000 0x00020000 { .ANY (+RO) }
}
"""
        with self.assertLogs(
                "membrowse.linker.keil_parser", level="WARNING") as cm:
            KeilScatterParser().parse(self._write(content))
        self.assertTrue(any("overlap" in m for m in cm.output))

    def test_exec_region_beyond_load_region_is_logged(self):
        # ER_1 ends at 0x08020000, past the load region end 0x08010000.
        content = """\
LR_1 0x08000000 0x00010000 {
  ER_1 0x08000000 0x00020000 { .ANY (+RO) }
}
"""
        with self.assertLogs(
                "membrowse.linker.keil_parser", level="WARNING") as cm:
            KeilScatterParser().parse(self._write(content))
        self.assertTrue(
            any("extends beyond" in m for m in cm.output), cm.output)

    def test_contained_exec_region_is_not_logged(self):
        # Well-formed: exec region fits inside the load region.
        content = """\
LR_1 0x08000000 0x00080000 {
  ER_1 0x08000000 0x00010000 { .ANY (+RO) }
}
"""
        logger_name = "membrowse.linker.keil_parser"
        with self.assertLogs(logger_name, level="WARNING") as cm:
            logging.getLogger(logger_name).warning("sentinel")
            KeilScatterParser().parse(self._write(content))
        self.assertFalse(
            any("extends beyond" in m or "overlap" in m for m in cm.output),
            cm.output)


class TestKeilOrchestration(_ScatterTestBase):
    """Tests parsing through the LinkerScriptParser orchestrator."""

    def test_transparent_dispatch(self):
        path = self._write(_STM32_SCATTER)
        result = LinkerScriptParser([path]).parse_memory_regions()

        self.assertEqual(set(result), {"ER_IROM1", "RW_IRAM1"})
        self.assertEqual(result["ER_IROM1"]["address"], 0x08000000)
        self.assertEqual(result["ER_IROM1"]["limit_size"], 0x00080000)
        self.assertEqual(result["RW_IRAM1"]["address"], 0x20000000)

    def test_mixed_with_gnu_ld(self):
        sct = self._write(_STM32_SCATTER, "app.sct")
        ld = self._write(_GNU_LD, "mem.ld")
        result = LinkerScriptParser([ld, sct]).parse_memory_regions()

        self.assertEqual(
            set(result), {"FLASH", "RAM", "ER_IROM1", "RW_IRAM1"})
        self.assertEqual(result["FLASH"]["limit_size"], 512 * 1024)
        self.assertEqual(result["ER_IROM1"]["limit_size"], 0x00080000)

    def test_non_utf8_scatter_dispatches(self):
        # Orchestrator reads scripts before Keil detection: a non-UTF-8 byte
        # must not raise UnicodeDecodeError before dispatch.
        path = self.temp_dir / "app.sct"
        path.write_bytes(
            ("; \xa9\n" + _STM32_SCATTER).encode("latin-1"))
        result = LinkerScriptParser([str(path)]).parse_memory_regions()
        self.assertEqual(set(result), {"ER_IROM1", "RW_IRAM1"})


if __name__ == '__main__':
    unittest.main()
