name: 'MemBrowse PR Memory Report'
description: 'Analyze memory usage of embedded firmware and upload report to MemBrowse'
author: 'MemBrowse'

inputs:
  elf:
    description: 'Path to ELF file'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target name like esp32, stm32f4'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: false
  api_url:
    description: 'MemBrowse API endpoint URL'
    required: false
    default: 'https://membrowse.appspot.com/api/upload'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install membrowse package
      shell: bash
      run: |
        pip install ${{ github.action_path }}/..
    
    - name: Run memory analysis
      shell: bash
      run: |
        ${{ github.action_path }}/../scripts/membrowse_new_commit.sh \
          "${{ inputs.elf }}" \
          "${{ inputs.ld }}" \
          "${{ inputs.target_name }}" \
          "${{ inputs.api_key }}" \
          "${{ inputs.api_url }}"

branding:
  icon: 'bar-chart-2'
  color: 'blue'