name: 'MemBrowse PR Memory Report'
description: 'Analyze memory footprint of embedded firmware and upload report to MemBrowse'
author: 'MemBrowse'

inputs:
  elf:
    description: 'Path to ELF file'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target name like esp32, stm32f4'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: false
  api_url:
    description: 'MemBrowse API endpoint URL'
    required: false
    default: 'https://www.membrowse.com/api/upload'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install membrowse package
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        if git describe --tags --exact-match HEAD 2>/dev/null | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+'; then
          echo "Installing from PyPI (tagged release)"
          pip install membrowse
        else
          echo "Installing from local source (main/development)"
          pip install "${{ github.action_path }}/.."
        fi
    
    - name: Run memory analysis
      shell: bash
      run: |
        membrowse report \
          "${{ inputs.elf }}" \
          "${{ inputs.ld }}" \
          --github \
          --target-name "${{ inputs.target_name }}" \
          --api-key "${{ inputs.api_key }}" \
          --api-url "${{ inputs.api_url }}"

branding:
  icon: 'bar-chart-2'
  color: 'blue'