name: 'MemBrowse PR Memory Report'
description: 'Analyze memory footprint of embedded firmware and upload report to MemBrowse'
author: 'MemBrowse'

inputs:
  elf:
    description: 'Path to ELF file'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target name like esp32, stm32f4'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: false
  api_url:
    description: 'MemBrowse API base URL (/api/upload appended automatically)'
    required: false
    default: 'https://www.membrowse.com'
  dont_fail_on_alerts:
    description: 'Continue even if budget alerts are detected (default: fail on alerts)'
    required: false
    default: 'false'
  pr_comment:
    description: 'Enable PR comment posting with memory changes (default: true)'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for posting PR comments (defaults to automatic github.token)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install membrowse package
      shell: bash
      run: |
        pip install ${{ github.action_path }}/..
    
    - name: Run memory analysis
      shell: bash
      run: |
        ARGS=(
          "${{ inputs.elf }}"
          "${{ inputs.ld }}"
          --github
          --target-name "${{ inputs.target_name }}"
          --api-key "${{ inputs.api_key }}"
          --api-url "${{ inputs.api_url }}"
          --output-url-file "${{ runner.temp }}/membrowse_url.txt"
        )

        if [ "${{ inputs.dont_fail_on_alerts }}" = "true" ]; then
          ARGS+=(--dont-fail-on-alerts)
        fi

        if [ "${{ inputs.pr_comment }}" = "true" ]; then
          ARGS+=(--pr-comment)
        fi

        membrowse report "${ARGS[@]}"

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.pr_comment == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
      run: |
        python -m membrowse.utils.github_comment --url-file "${{ runner.temp }}/membrowse_url.txt"

branding:
  icon: 'bar-chart-2'
  color: 'blue'