#!/usr/bin/env python3
"""
IAR ELF Linker map file parser for symbol-to-object-file mapping.

Parses map files generated by the IAR ELF Linker (EWARM).
"""

import re
from typing import Dict, Tuple


# Match IAR PLACEMENT SUMMARY contribution lines:
#   .text              ro code  0x000000e0  0x3040  HART.o [1]
#   .rodata            const    0x0000515c   0xc8  system.o [1]
#   .bss               zero     0x20000000   0x200  main.o [1]
#   .text              ro code  0x800'0130  0x10c6  xprintffull.o [2]
#   __DLIB_PERTHREAD   inited   0x20000008    0x88  localeconv.o [3]
#   CODE               ro code  0x800'5894    0x88  portasm.o [1]
# Note: Kind field can be multi-word ("ro code", "ro data")
# Note: Addresses may use ' as digit separator (e.g. 0x800'0000)
# Note: Section names may not start with '.' (e.g. CODE, __DLIB_PERTHREAD)
_IAR_PLACEMENT_RE = re.compile(
    r'^\s+(\S+)\s+'             # group 1: section name
    r'.+?'                      # kind (ro code, const, zero, uninit - may have spaces)
    r"(0x[0-9a-fA-F']+)\s+"    # group 2: address (may have ' separators)
    r"(0x[0-9a-fA-F']+)\s+"    # group 3: size (may have ' separators)
    r'(\S+\.o)\s+'              # group 4: object file
    r'\[(\d+)\]'                # group 5: module group index
)

# Match IAR MODULE SUMMARY group header:
#   dl7M_tlf.a: [3]
#   C:\path\to\Debug\Obj: [1]
_IAR_MODULE_GROUP_RE = re.compile(
    r'^(\S.*?):\s+\[(\d+)\]'   # group 1: library/path, group 2: index
)


class IARMapFileParser:  # pylint: disable=too-few-public-methods
    """Parse IAR ELF Linker map files to extract address-to-object mappings."""

    def parse(self, content: str) -> Dict[int, Tuple[str, str]]:
        """Parse IAR map file content.

        Parses MODULE SUMMARY to build group-index-to-library mapping,
        then parses PLACEMENT SUMMARY for address-to-object entries.

        Args:
            content: Full text content of an IAR map file.

        Returns:
            Dict mapping integer addresses to (archive, object_file) tuples.
            Archive is the library name (e.g. "dl7M_tlf.a") or "" for
            object files from the project directory.
        """
        group_to_library = self._parse_module_summary(content)
        return self._parse_placement_summary(content, group_to_library)

    def _parse_module_summary(self, content: str) -> Dict[str, str]:
        """Extract group index -> library/path mapping from MODULE SUMMARY.

        Returns:
            Dict mapping group index string to library name.
            Project directories (paths ending without .a) map to "".
        """
        group_map: Dict[str, str] = {}
        in_module_summary = False

        for line in content.splitlines():
            if '*** MODULE SUMMARY' in line:
                in_module_summary = True
                continue
            if in_module_summary and line.startswith('*****'):
                break

            if not in_module_summary:
                continue

            match = _IAR_MODULE_GROUP_RE.match(line)
            if match:
                name = match.group(1).strip()
                index = match.group(2)
                # Library archives end with .a, project dirs don't
                if name.endswith('.a'):
                    group_map[index] = name
                else:
                    group_map[index] = ''

        return group_map

    def _parse_placement_summary(
        self, content: str, group_to_library: Dict[str, str]
    ) -> Dict[int, Tuple[str, str]]:
        """Extract address-to-object mappings from PLACEMENT SUMMARY."""
        mappings: Dict[int, Tuple[str, str]] = {}
        in_placement = False

        for line in content.splitlines():
            if '*** PLACEMENT SUMMARY' in line:
                in_placement = True
                continue
            if in_placement and line.startswith('*****'):
                break

            if not in_placement:
                continue

            match = _IAR_PLACEMENT_RE.match(line)
            if not match:
                continue

            address = int(match.group(2).replace("'", ""), 16)
            if address == 0:
                continue

            obj = match.group(4)
            group_idx = match.group(5)
            archive = group_to_library.get(group_idx, '')

            if address not in mappings:
                mappings[address] = (archive, obj)

        return mappings
