#!/usr/bin/env python3
"""
IAR ELF Linker map file parser for symbol-to-object-file mapping.

Parses map files generated by the IAR ELF Linker (EWARM).
"""

import re
from typing import Dict, List, Tuple

from ._maprange import RangeAccumulator


# Match IAR PLACEMENT SUMMARY contribution lines. Two layouts seen in the wild:
#
#   5-col:  Section Kind  Address  Size  Object [N]
#     .text    ro code  0x000000e0  0x3040  main.o [1]
#     .text    ro code  0x800'0130  0x10c6  xprintffull.o [2]
#
#   6-col:  Section Kind  Address  Alignment  Size  Object [N]
#     .text    ro code  0x000000e0          4  0x3040  main.o [1]
#
# Wrapped section names: when a long section name does not fit it occupies its
# own line, and the data follows on the next line starting at the kind column.
# The leading token captured in group 1 is then the kind, not the section name;
# the resolver only consumes the address range and object so this is harmless.
#
# Note: Kind may be multi-word ("ro code", "ro data") or absent.
# Note: Addresses may use ' as digit separator (e.g. 0x800'0000).
# Note: Section names need not start with '.' (e.g. CODE, __DLIB_PERTHREAD).
_IAR_PLACEMENT_RE = re.compile(
    r'^\s+(\S+)\s+'             # group 1: section name (or kind on a wrapped line)
    r'.+?'                      # kind (may be empty or contain whitespace)
    r"(0x[0-9a-fA-F']+)\s+"    # group 2: address (may have ' separators)
    r"(?:\d+\s+)?"              # optional alignment column (decimal integer)
    r"(0x[0-9a-fA-F']+)\s+"    # group 3: size (may have ' separators)
    r'(\S+\.o)\s+'              # group 4: object file
    r'\[(\d+)\]'                # group 5: module group index
)

# Match IAR MODULE SUMMARY group header:
#   dl7M_tlf.a: [3]
#   C:\path\to\Debug\Obj: [1]
_IAR_MODULE_GROUP_RE = re.compile(
    r'^(\S.*?):\s+\[(\d+)\]'   # group 1: library/path, group 2: index
)


class IARMapFileParser:  # pylint: disable=too-few-public-methods
    """Parse IAR ELF Linker map files to extract address-to-object mappings."""

    def parse(self, content: str) -> List[Tuple[int, int, str, str]]:
        """Parse IAR map file content.

        Parses MODULE SUMMARY to build group-index-to-library mapping,
        then parses PLACEMENT SUMMARY for per-section contribution ranges.

        Each PLACEMENT entry covers an entire object's contribution to a
        section (typically thousands of bytes containing many ELF symbols).
        We emit half-open ranges ``[start, start+size)`` so the resolver
        can attribute every interior symbol, not just the one at the
        section start.

        Args:
            content: Full text content of an IAR map file.

        Returns:
            List of ``(start, end, archive, object_file)`` tuples sorted by
            ``start``. ``archive`` is the library name (e.g. "dl7M_tlf.a")
            or "" for object files from the project directory.
        """
        group_to_library = self._parse_module_summary(content)
        return self._parse_placement_summary(content, group_to_library)

    def _parse_module_summary(self, content: str) -> Dict[str, str]:
        """Extract group index -> library/path mapping from MODULE SUMMARY.

        Returns:
            Dict mapping group index string to library name.
            Project directories (paths ending without .a) map to "".
        """
        group_map: Dict[str, str] = {}
        in_module_summary = False

        for line in content.splitlines():
            if '*** MODULE SUMMARY' in line:
                in_module_summary = True
                continue
            if in_module_summary and line.startswith('*****'):
                break

            if not in_module_summary:
                continue

            match = _IAR_MODULE_GROUP_RE.match(line)
            if match:
                name = match.group(1).strip()
                index = match.group(2)
                # Library archives end with .a, project dirs don't
                if name.endswith('.a'):
                    group_map[index] = name
                else:
                    group_map[index] = ''

        return group_map

    def _parse_placement_summary(
        self, content: str, group_to_library: Dict[str, str]
    ) -> List[Tuple[int, int, str, str]]:
        """Extract per-section contribution ranges from PLACEMENT SUMMARY."""
        acc = RangeAccumulator()
        in_placement = False

        for line in content.splitlines():
            if '*** PLACEMENT SUMMARY' in line:
                in_placement = True
                continue
            if in_placement and line.startswith('*****'):
                break

            if not in_placement:
                continue

            match = _IAR_PLACEMENT_RE.match(line)
            if not match:
                continue

            address = int(match.group(2).replace("'", ""), 16)
            size = int(match.group(3).replace("'", ""), 16)
            obj = match.group(4)
            group_idx = match.group(5)
            archive = group_to_library.get(group_idx, '')
            acc.add(address, size, archive, obj)

        return acc.finalize()
