#!/usr/bin/env python3
"""
Linker map file parser for symbol-to-object-file mapping.

Supports two map file formats:
- **GNU LD**: Generated via ``-Wl,-Map=output.map`` (GCC, Clang, Rust)
- **IAR**: Generated by the IAR ELF Linker (EWARM)

The format is auto-detected by :meth:`MapFileResolver.from_file`.
"""

import logging
from typing import Dict, Tuple

from ..core.exceptions import MapFileParseError
from .ldmap_parser import MapFileParser
from .iarmap_parser import IARMapFileParser

logger = logging.getLogger(__name__)

# Re-export parsers for backwards compatibility
__all__ = [
    'MapFileParser',
    'IARMapFileParser',
    'MapFileResolver',
]


def _detect_map_format(content: str) -> str:
    """Detect whether a map file is GNU LD or IAR format.

    Args:
        content: Map file text content.

    Returns:
        "iar" or "gnu_ld".
    """
    if '*** PLACEMENT SUMMARY' in content or 'IAR ELF Linker' in content:
        return 'iar'
    return 'gnu_ld'


class MapFileResolver:
    """Resolve symbol addresses to their originating archive/object files.

    This follows the same pattern as SourceFileResolver: constructed once
    from pre-parsed data and injected into SymbolExtractor for per-symbol
    lookups.
    """

    def __init__(self, address_map: Dict[int, Tuple[str, str]]):
        """Initialize with pre-parsed address mapping.

        Args:
            address_map: Dict mapping addresses to (archive, object_file) tuples.
        """
        self._address_map = address_map

    @classmethod
    def from_file(cls, map_path: str) -> 'MapFileResolver':
        """Create a resolver by parsing a map file (GNU LD or IAR).

        The format is auto-detected from the file content.

        Args:
            map_path: Path to the .map file.

        Returns:
            MapFileResolver with parsed address mappings.

        Raises:
            MapFileParseError: If the file cannot be read.
        """
        try:
            with open(map_path, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
        except OSError as e:
            raise MapFileParseError(
                f"Cannot read map file {map_path}: {e}") from e

        fmt = _detect_map_format(content)
        if fmt == 'iar':
            parser = IARMapFileParser()
            logger.info("Detected IAR map file format: %s", map_path)
        else:
            parser = MapFileParser()
            logger.info("Detected GNU LD map file format: %s", map_path)

        address_map = parser.parse(content)
        if not address_map and content.strip():
            logger.warning(
                "Map file %s produced no address entries - "
                "check that the format is correct", map_path)
        else:
            logger.info("Map file parsed: %d address entries from %s",
                         len(address_map), map_path)
        return cls(address_map)

    @classmethod
    def null(cls) -> 'MapFileResolver':
        """Create a no-op resolver (used when no map file is provided).

        Returns:
            MapFileResolver with empty mapping.
        """
        return cls({})

    def resolve(self, address: int) -> Tuple[str, str]:
        """Look up the archive and object file for a symbol address.

        Args:
            address: Symbol virtual address from ELF symtab.

        Returns:
            (archive, object_file) tuple, or ("", "") if not found.
        """
        result = self._address_map.get(address)
        if result is not None:
            return result
        # ARM Thumb functions have bit 0 set in st_value; map files use
        # the real (even) load address. Try with bit 0 cleared.
        return self._address_map.get(address & ~1, ('', ''))
