#!/usr/bin/env python3
"""
Linker map file parser for symbol-to-object-file mapping.

Supports two map file formats:
- **GNU LD**: Generated via ``-Wl,-Map=output.map`` (GCC, Clang, Rust)
- **IAR**: Generated by the IAR ELF Linker (EWARM)

The format is auto-detected by :meth:`MapFileResolver.from_file`.
"""

import re
import logging
from typing import Dict, Tuple

from ..core.exceptions import MapFileParseError

logger = logging.getLogger(__name__)

# Match input section contribution lines (indented):
#   .text          0x0000000008000010       0xac path/to/file.o
#   .text          0x0000000008000010       0xac libfoo.a(bar.o)
#   COMMON         0x20001ee0        0x4 main.o
_SECTION_CONTRIB_RE = re.compile(
    r'^\s+(\.\S+|COMMON)\s+'    # group 1: section name (indented), or COMMON
    r'(0x[0-9a-fA-F]+)\s+'      # group 2: address
    r'(0x[0-9a-fA-F]+)\s+'      # group 3: size
    r'(.+)$'                     # group 4: file/archive path
)

# Match archive(object) pattern: libfoo.a(bar.o)
_ARCHIVE_RE = re.compile(r'^(.+\.a)\((.+\.o)\)$')


class MapFileParser:
    """Parse GNU LD map file content to extract address-to-object mappings."""

    def parse(self, content: str) -> Dict[int, Tuple[str, str]]:
        """Parse map file content and return address->(archive, object_file) mapping.

        Args:
            content: Full text content of a GNU LD map file.

        Returns:
            Dict mapping integer addresses to (archive, object_file) tuples.
            Archive is empty string when symbol comes from a bare .o file.
        """
        mappings: Dict[int, Tuple[str, str]] = {}

        for line in content.splitlines():
            match = _SECTION_CONTRIB_RE.match(line)
            if not match:
                continue

            address = int(match.group(2), 16)
            if address == 0:
                continue

            file_field = match.group(4).strip()
            archive, obj = self._parse_file_field(file_field)
            if obj:
                # First occurrence wins (GNU LD lists in link order)
                if address not in mappings:
                    mappings[address] = (archive, obj)

        return mappings

    @staticmethod
    def _parse_file_field(field: str) -> Tuple[str, str]:
        """Parse the file/archive field from a map file line.

        Returns:
            (archive, object_file) tuple. Archive is "" for bare .o files.
            Both are ("", "") for linker-synthetic entries.
        """
        if not field or field == 'linker stubs' or field.startswith('*fill*'):
            return ('', '')

        archive_match = _ARCHIVE_RE.match(field)
        if archive_match:
            return (archive_match.group(1), archive_match.group(2))

        if field.endswith('.o'):
            return ('', field)

        return ('', '')


# IAR map file patterns
# Match IAR PLACEMENT SUMMARY contribution lines:
#   .text              ro code  0x000000e0  0x3040  HART.o [1]
#   .rodata            const    0x0000515c   0xc8  system.o [1]
#   .bss               zero     0x20000000   0x200  main.o [1]
#   .text              ro code  0x800'0130  0x10c6  xprintffull.o [2]
#   __DLIB_PERTHREAD   inited   0x20000008    0x88  localeconv.o [3]
#   CODE               ro code  0x800'5894    0x88  portasm.o [1]
# Note: Kind field can be multi-word ("ro code", "ro data")
# Note: Addresses may use ' as digit separator (e.g. 0x800'0000)
# Note: Section names may not start with '.' (e.g. CODE, __DLIB_PERTHREAD)
_IAR_PLACEMENT_RE = re.compile(
    r'^\s+(\S+)\s+'             # group 1: section name
    r'.+?'                      # kind (ro code, const, zero, uninit - may have spaces)
    r"(0x[0-9a-fA-F']+)\s+"    # group 2: address (may have ' separators)
    r"(0x[0-9a-fA-F']+)\s+"    # group 3: size (may have ' separators)
    r'(\S+\.o)\s+'              # group 4: object file
    r'\[(\d+)\]'                # group 5: module group index
)

# Match IAR MODULE SUMMARY group header:
#   dl7M_tlf.a: [3]
#   C:\path\to\Debug\Obj: [1]
_IAR_MODULE_GROUP_RE = re.compile(
    r'^(\S.*?):\s+\[(\d+)\]'   # group 1: library/path, group 2: index
)


class IARMapFileParser:
    """Parse IAR ELF Linker map files to extract address-to-object mappings."""

    def parse(self, content: str) -> Dict[int, Tuple[str, str]]:
        """Parse IAR map file content.

        Parses MODULE SUMMARY to build group-index-to-library mapping,
        then parses PLACEMENT SUMMARY for address-to-object entries.

        Args:
            content: Full text content of an IAR map file.

        Returns:
            Dict mapping integer addresses to (archive, object_file) tuples.
            Archive is the library name (e.g. "dl7M_tlf.a") or "" for
            object files from the project directory.
        """
        group_to_library = self._parse_module_summary(content)
        return self._parse_placement_summary(content, group_to_library)

    def _parse_module_summary(self, content: str) -> Dict[str, str]:
        """Extract group index -> library/path mapping from MODULE SUMMARY.

        Returns:
            Dict mapping group index string to library name.
            Project directories (paths ending without .a) map to "".
        """
        group_map: Dict[str, str] = {}
        in_module_summary = False

        for line in content.splitlines():
            if '*** MODULE SUMMARY' in line:
                in_module_summary = True
                continue
            if in_module_summary and line.startswith('*****'):
                break

            if not in_module_summary:
                continue

            match = _IAR_MODULE_GROUP_RE.match(line)
            if match:
                name = match.group(1).strip()
                index = match.group(2)
                # Library archives end with .a, project dirs don't
                if name.endswith('.a'):
                    group_map[index] = name
                else:
                    group_map[index] = ''

        return group_map

    def _parse_placement_summary(
        self, content: str, group_to_library: Dict[str, str]
    ) -> Dict[int, Tuple[str, str]]:
        """Extract address-to-object mappings from PLACEMENT SUMMARY."""
        mappings: Dict[int, Tuple[str, str]] = {}
        in_placement = False

        for line in content.splitlines():
            if '*** PLACEMENT SUMMARY' in line:
                in_placement = True
                continue
            if in_placement and line.startswith('*****'):
                break

            if not in_placement:
                continue

            match = _IAR_PLACEMENT_RE.match(line)
            if not match:
                continue

            address = int(match.group(2).replace("'", ""), 16)
            if address == 0:
                continue

            obj = match.group(4)
            group_idx = match.group(5)
            archive = group_to_library.get(group_idx, '')

            if address not in mappings:
                mappings[address] = (archive, obj)

        return mappings


def _detect_map_format(content: str) -> str:
    """Detect whether a map file is GNU LD or IAR format.

    Args:
        content: Map file text content.

    Returns:
        "iar" or "gnu_ld".
    """
    if '*** PLACEMENT SUMMARY' in content or 'IAR ELF Linker' in content:
        return 'iar'
    return 'gnu_ld'


class MapFileResolver:
    """Resolve symbol addresses to their originating archive/object files.

    This follows the same pattern as SourceFileResolver: constructed once
    from pre-parsed data and injected into SymbolExtractor for per-symbol
    lookups.
    """

    def __init__(self, address_map: Dict[int, Tuple[str, str]]):
        """Initialize with pre-parsed address mapping.

        Args:
            address_map: Dict mapping addresses to (archive, object_file) tuples.
        """
        self._address_map = address_map

    @classmethod
    def from_file(cls, map_path: str) -> 'MapFileResolver':
        """Create a resolver by parsing a map file (GNU LD or IAR).

        The format is auto-detected from the file content.

        Args:
            map_path: Path to the .map file.

        Returns:
            MapFileResolver with parsed address mappings.

        Raises:
            MapFileParseError: If the file cannot be read.
        """
        try:
            with open(map_path, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
        except OSError as e:
            raise MapFileParseError(
                f"Cannot read map file {map_path}: {e}") from e

        fmt = _detect_map_format(content)
        if fmt == 'iar':
            parser = IARMapFileParser()
            logger.info("Detected IAR map file format: %s", map_path)
        else:
            parser = MapFileParser()
            logger.info("Detected GNU LD map file format: %s", map_path)

        address_map = parser.parse(content)
        logger.info("Map file parsed: %d address entries from %s",
                     len(address_map), map_path)
        return cls(address_map)

    @classmethod
    def null(cls) -> 'MapFileResolver':
        """Create a no-op resolver (used when no map file is provided).

        Returns:
            MapFileResolver with empty mapping.
        """
        return cls({})

    def resolve(self, address: int) -> Tuple[str, str]:
        """Look up the archive and object file for a symbol address.

        Args:
            address: Symbol virtual address from ELF symtab.

        Returns:
            (archive, object_file) tuple, or ("", "") if not found.
        """
        return self._address_map.get(address, ('', ''))
