name: 'MemBrowse Onboard Historical Analysis'
description: 'Analyze memory usage across historical commits for embedded firmware onboarding'
author: 'MemBrowse'

inputs:
  num_commits:
    description: 'Number of historical commits to process'
    required: true
  build_script:
    description: 'Shell command to build the firmware'
    required: true
  elf:
    description: 'Path to generated ELF file after build'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target platform name'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
    
    - name: Install Google Bloaty
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          # Linux: use Homebrew (bloaty not available in apt repositories)
          if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
          brew install bloaty
          echo "Installed Bloaty via Homebrew on Linux"
          
          # Add Homebrew to PATH for subsequent steps
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          # macOS: use Homebrew
          brew install bloaty
          echo "Installed Bloaty via Homebrew on macOS"
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "Error: Bloaty is not supported on Windows runners"
          echo "Please use Linux or macOS runners for memory analysis"
          exit 1
        else
          echo "Error: Unsupported runner OS: $RUNNER_OS"
          exit 1
        fi
        
        # Verify installation
        bloaty --version
    
    - name: Fetch full git history
      shell: bash
      run: |
        git fetch --unshallow || true
        git fetch --all
    
    - name: Run historical analysis
      shell: bash
      run: |
        ${{ github.action_path }}/entrypoint.sh \
          "${{ inputs.num_commits }}" \
          "${{ inputs.build_script }}" \
          "${{ inputs.elf }}" \
          "${{ inputs.ld }}" \
          "${{ inputs.target_name }}" \
          "${{ inputs.api_key }}"

branding:
  icon: 'clock'
  color: 'green'