name: 'MemBrowse Onboard Historical Analysis'
description: 'Analyze memory usage across historical commits for embedded firmware onboarding'
author: 'MemBrowse'

inputs:
  num_commits:
    description: 'Number of historical commits to process'
    required: true
  build_script:
    description: 'Shell command to build the firmware'
    required: true
  elf:
    description: 'Path to generated ELF file after build'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target platform name'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install membrowse package
      shell: bash
      run: |
        echo "=== MEMBROWSE-ACTION VERSION ==="
        cd ${{ github.action_path }}/..
        echo "Action path: ${{ github.action_path }}"
        git log -1 --oneline 2>/dev/null || echo "Not a git repo"
        git rev-parse HEAD 2>/dev/null || echo "No git HEAD"
        cat setup.py | grep version || echo "No version in setup.py"
        echo "================================"
        pip install --force-reinstall --no-cache-dir ${{ github.action_path }}/..
    
    - name: Fetch full git history
      shell: bash
      run: |
        git fetch --unshallow || true
        git fetch --all
    
    - name: Run historical analysis
      shell: bash
      env:
        MEMBROWSE_UPLOAD_URL: https://membrowse.appspot.com/api/upload
        STOP_AFTER_FIRST: "1"
        DEBUG_MODE: "1"
        DEBUG_REPORT_PATH: "./debug_report.json"
      run: |
        ${{ github.action_path }}/../scripts/onboard.sh \
          "${{ inputs.num_commits }}" \
          "${{ inputs.build_script }}" \
          "${{ inputs.elf }}" \
          "${{ inputs.ld }}" \
          "${{ inputs.target_name }}" \
          "${{ inputs.api_key }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: firmware-artifacts-${{ inputs.target_name }}
        path: |
          ${{ inputs.elf }}
        retention-days: 7

    - name: Upload debug report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-report-${{ inputs.target_name }}
        path: |
          ./debug_report*.json
        retention-days: 7

branding:
  icon: 'clock'
  color: 'green'