name: 'MemBrowse - Historical Memory Baseline'
description: 'Analyze memory usage across past commits to establish an initial baseline.'
author: 'MemBrowse'

inputs:
  num_commits:
    description: 'Number of historical commits to process'
    required: true
  build_script:
    description: 'Shell command to build the firmware'
    required: true
  elf:
    description: 'Path to generated ELF file after build'
    required: true
  ld:
    description: 'Space-separated list of linker script paths'
    required: true
  target_name:
    description: 'Target platform name'
    required: true
  api_key:
    description: 'API key for MemBrowse'
    required: true
  api_url:
    description: 'MemBrowse API base URL (/api/upload appended automatically)'
    required: false
    default: 'https://www.membrowse.com'
  linker_vars:
    description: 'Space-separated linker variable definitions (e.g., "__micropy_flash_size__=4096K RAM_START=0x20000000")'
    required: false
    default: ''
  verbose:
    description: 'Set logging level: DEBUG, INFO, or WARNING (default: WARNING)'
    required: false
    default: 'WARNING'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install membrowse package
      shell: bash
      run: |
        pip install --force-reinstall --no-cache-dir ${{ github.action_path }}/..
    
    - name: Fetch full git history
      shell: bash
      run: |
        git fetch --unshallow || true
        git fetch --all
    
    - name: Run historical analysis
      shell: bash
      run: |
        # Global args (before subcommand)
        GLOBAL_ARGS=()
        if [ "${{ inputs.verbose }}" != "WARNING" ]; then
          GLOBAL_ARGS+=(--verbose "${{ inputs.verbose }}")
        fi

        # Subcommand args
        ONBOARD_ARGS=(
          "${{ inputs.num_commits }}"
          "${{ inputs.build_script }}"
          "${{ inputs.elf }}"
          "${{ inputs.ld }}"
          "${{ inputs.target_name }}"
          "${{ inputs.api_key }}"
        )

        # Only pass api_url if explicitly provided and non-empty
        if [ -n "${{ inputs.api_url }}" ]; then
          ONBOARD_ARGS+=("${{ inputs.api_url }}")
        fi

        # Add linker variable definitions
        if [ -n "${{ inputs.linker_vars }}" ]; then
          for var in ${{ inputs.linker_vars }}; do
            ONBOARD_ARGS+=(--def "$var")
          done
        fi

        membrowse "${GLOBAL_ARGS[@]}" onboard "${ONBOARD_ARGS[@]}"

branding:
  icon: 'clock'
  color: 'green'